In [37]:
import pandas as pd

# Veri setinin dosya yolunu tanımlama
file_path = 'bank.csv'

# Veri setini yükleme
try:
    data = pd.read_csv(file_path)
    print("Veri seti başarıyla yüklendi.")
except FileNotFoundError:
    print(f"Hata: {file_path} yolu bulunamadı. Lütfen dosya yolunu kontrol edin.")
except Exception as e:
    print(f"Bir hata oluştu: {e}")

# Veri setinin ilk birkaç satırını gösterme
print(data.head())

Veri seti başarıyla yüklendi.
  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  30;"unemployed";"married";"primary";"no";1787;...
1  33;"services";"married";"secondary";"no";4789;...
2  35;"management";"single";"tertiary";"no";1350;...
3  30;"management";"married";"tertiary";"no";1476...
4  59;"blue-collar";"married";"secondary";"no";0;...

In [38]:
data = pd.read_csv(file_path, delimiter=';')

data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [39]:
import pandas as pd

file_path = 'bank.csv'
data = pd.read_csv(file_path, delimiter=';')

# Veri setinin ilk birkaç satırına göz atarak yapısını kontrol etme
print("Veri setinin ilk birkaç satırı:")
print(data.head())

# Veri setinin yapısını genel olarak anlama
print("\nVeri seti hakkında genel bilgi:")
print(data.info())

# Sayısal sütunlara dair özet istatistikleri görüntüleme
print("\nVeri setinin sayısal sütunları için özet istatistikler:")
print(data.describe())

Veri setinin ilk birkaç satırı:
   age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no
1   33     services  married  secondary      no     4789     yes  yes
2   35   management   single   tertiary      no     1350     yes   no
3   30   management  married   tertiary      no     1476     yes  yes
4   59  blue-collar  married  secondary      no        0     yes   no

    contact  day month  duration  campaign  pdays  previous poutcome   y
0  cellular   19   oct        79         1     -1         0  unknown  no
1  cellular   11   may       220         1    339         4  failure  no
2  cellular   16   apr       185         1    330         1  failure  no
3   unknown    3   jun       199         4     -1         0  unknown  no
4   unknown    5   may       226         1     -1         0  unknown  no

Veri seti hakkında genel bilgi:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB
None

Veri setinin sayısal sütunları için özet istatistikler:
               age       balance          day     duration     campaign  \
count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000
mean     41.170095   1422.657819    15.915284   263.961292     2.793630
std      10.576211   3009.638142     8.247667   259.856633     3.109807
min      19.000000  -3313.000000     1.000000     4.000000     1.000000
25%      33.000000     69.000000     9.000000   104.000000     1.000000
50%      39.000000    444.000000    16.000000   185.000000     2.000000
75%      49.000000   1480.000000    21.000000   329.000000     3.000000
max      87.000000  71188.000000    31.000000  3025.000000    50.000000

             pdays     previous
count  4521.000000  4521.000000
mean     39.766645     0.542579
std     100.121124     1.693562
min      -1.000000     0.000000
25%      -1.000000     0.000000
50%      -1.000000     0.000000
75%      -1.000000     0.000000
max     871.000000    25.000000

In [40]:
import pandas as pd

# Eksik verileri kontrol et
print("Eksik veri sayısı (her sütun için):")
print(data.isnull().sum())

# Eksik verileri doldurma
for column in data.columns:
    if data[column].dtype == 'object':  # Kategorik sütunlar
        data[column] = data[column].fillna(data[column].mode()[0])
    else:  # Sayısal sütunlar
        data[column] = data[column].fillna(data[column].median())

# Eksik verilerin doldurulduktan sonraki durumunu kontrol eder
print("\nEksik veri sayısı (doldurduktan sonra):")
print(data.isnull().sum())

Eksik veri sayısı (her sütun için):
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

Eksik veri sayısı (doldurduktan sonra):
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [41]:
import numpy as np

# Sayısal sütunlardaki aykırı değerleri alt ve üst sınırlara eşitleme
for column in data.select_dtypes(include=[np.number]).columns:
    Q1 = data[column].quantile(0.25)  # 1. çeyrek (25. yüzde)
    Q3 = data[column].quantile(0.75)  # 3. çeyrek (75. yüzde)
    IQR = Q3 - Q1  # Çeyrekler arası mesafe

    # Alt ve üst sınırları hesapla
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    # Değerleri alt ve üst sınırlara eşitleme
    data[column] = np.clip(data[column], lower_limit, upper_limit)

print("Aykırı değerler IQR yöntemi ile sınırlandırıldı.")
print(data.describe())

Aykırı değerler IQR yöntemi ile sınırlandırıldı.
               age      balance          day     duration     campaign  \
count  4521.000000  4521.000000  4521.000000  4521.000000  4521.000000
mean     41.123203   973.493696    15.915284   241.785667     2.412962
std      10.416974  1240.356566     8.247667   185.397346     1.622028
min      19.000000 -2047.500000     1.000000     4.000000     1.000000
25%      33.000000    69.000000     9.000000   104.000000     1.000000
50%      39.000000   444.000000    16.000000   185.000000     2.000000
75%      49.000000  1480.000000    21.000000   329.000000     3.000000
max      73.000000  3596.500000    31.000000   666.500000     6.000000

        pdays  previous
count  4521.0    4521.0
mean     -1.0       0.0
std       0.0       0.0
min      -1.0       0.0
25%      -1.0       0.0
50%      -1.0       0.0
75%      -1.0       0.0
max      -1.0       0.0

In [42]:
from sklearn.preprocessing import LabelEncoder

# Kategorik sütunları seçer
categorical_columns = data.select_dtypes(include=['object']).columns

# LabelEncoder ile kategorik sütunları sayısal değerlere dönüştürür
label_encoder = LabelEncoder()
for column in categorical_columns:
    data[column] = label_encoder.fit_transform(data[column])

# Sonuçları kontrol eder
print("Kategorik değişkenler sayısal değerlere dönüştürüldü.")
print(data.head())

Kategorik değişkenler sayısal değerlere dönüştürüldü.
   age  job  marital  education  default  balance  housing  loan  contact  \
0   30   10        1          0        0   1787.0        0     0        0
1   33    7        1          1        0   3596.5        1     1        0
2   35    4        2          2        0   1350.0        1     0        0
3   30    4        1          2        0   1476.0        1     1        2
4   59    1        1          1        0      0.0        1     0        2

   day  month  duration  campaign  pdays  previous  poutcome  y
0   19     10      79.0         1     -1         0         3  0
1   11      8     220.0         1     -1         0         0  0
2   16      0     185.0         1     -1         0         0  0
3    3      6     199.0         4     -1         0         3  0
4    5      8     226.0         1     -1         0         3  0

In [43]:
# Kategorik sütunları one-hot encoding ile dönüştür
data = pd.get_dummies(data, columns=categorical_columns)

# Sonuçları kontrol et
print("Kategorik değişkenler One-Hot Encoding ile sayısal değerlere dönüştürüldü.")
print(data.head())

Kategorik değişkenler One-Hot Encoding ile sayısal değerlere dönüştürüldü.
   age  balance  day  duration  campaign  pdays  previous  job_0  job_1  \
0   30   1787.0   19      79.0         1     -1         0  False  False
1   33   3596.5   11     220.0         1     -1         0  False  False
2   35   1350.0   16     185.0         1     -1         0  False  False
3   30   1476.0    3     199.0         4     -1         0  False  False
4   59      0.0    5     226.0         1     -1         0  False   True

   job_2  ...  month_8  month_9  month_10  month_11  poutcome_0  poutcome_1  \
0  False  ...    False    False      True     False       False       False
1  False  ...     True    False     False     False        True       False
2  False  ...    False    False     False     False        True       False
3  False  ...    False    False     False     False       False       False
4  False  ...     True    False     False     False       False       False

   poutcome_2  poutcome_3   y_0    y_1
0       False        True  True  False
1       False       False  True  False
2       False       False  True  False
3       False        True  True  False
4       False        True  True  False

[5 rows x 53 columns]

In [44]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

data = pd.read_csv('bank.csv', delimiter=';')

# Sayısal sütunları seçer
numerical_columns = data.select_dtypes(include=[np.number]).columns

# Min-Max Scaler'ı tanımlar
scaler = MinMaxScaler()

# Sayısal sütunları normalize eder
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

# Sonuçları kontrol eder
print("Sayısal sütunlar Min-Max normalizasyonu ile normalize edildi.")
print(data[numerical_columns].head())

Sayısal sütunlar Min-Max normalizasyonu ile normalize edildi.
        age   balance       day  duration  campaign     pdays  previous
0  0.161765  0.068455  0.600000  0.024826  0.000000  0.000000      0.00
1  0.205882  0.108750  0.333333  0.071500  0.000000  0.389908      0.16
2  0.235294  0.062590  0.500000  0.059914  0.000000  0.379587      0.04
3  0.161765  0.064281  0.066667  0.064548  0.061224  0.000000      0.00
4  0.588235  0.044469  0.133333  0.073486  0.000000  0.000000      0.00

In [45]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

# Özellikler ve hedef değişkeni ayırma
X_train = train_data.drop(columns=['y'])  # Eğitim setinden hedef değişkeni çıkarır
y_train = train_data['y']                  # Eğitim setindeki hedef değişken
X_test = test_data.drop(columns=['y'])     # Test setinden hedef değişkeni çıkarır
y_test = test_data['y']                    # Test setindeki hedef değişken

# KNN sınıflayıcıyı başlatma
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')  # K=5 komşu ve Öklid mesafesi kullan

# Modeli eğitme
knn.fit(X_train, y_train)

# Test seti üzerinde tahmin yapma
y_pred = knn.predict(X_test)

# Performans metriklerini hesaplama
accuracy = accuracy_score(y_test, y_pred)                   # Doğruluk
precision = precision_score(y_test, y_pred)                 # Hassasiyet
recall = recall_score(y_test, y_pred)                       # Hatırlama
f1 = f1_score(y_test, y_pred)                               # F1 Puanı

# Diğer metrikleri türetmek için karışıklık matrisini hesaplama
conf_matrix = confusion_matrix(y_test, y_pred)              # Karışıklık matrisi
TN, FP, FN, TP = conf_matrix.ravel()                        # Gerçek pozitif, gerçek negatif, yanlış pozitif, yanlış negatif
specificity = TN / (TN + FP)                                # Özgüllük
false_alarm_rate = FP / (FP + TN)                            # Yanlış alarm oranı

# Sonuçları görüntüleme
metrics = {
    "Doğruluk": accuracy,
    "Hata Oranı": 1 - accuracy,
    "Hatırlama": recall,
    "Hassasiyet": precision,
    "Özgüllük": specificity,
    "Yanlış Alarm Oranı": false_alarm_rate,
    "F1 Puanı": f1
}

metrics

{'Doğruluk': 0.8816503800217155,
 'Hata Oranı': 0.11834961997828453,
 'Hatırlama': 0.14414414414414414,
 'Hassasiyet': 0.5333333333333333,
 'Özgüllük': 0.9827160493827161,
 'Yanlış Alarm Oranı': 0.01728395061728395,
 'F1 Puanı': 0.22695035460992907}